version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: false
http:
  addr: :5000
  host: https://private.repo.goes.here
  headers:
    X-Content-Type-Options: [nosniff]
    #  tls:
    #    certificate: /certs/live/private.repo.goes.here/fullchain.pem
    #    key: /certs/live/private.repo.goes.here/privkey.pem
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
