version: '3.3'
services:
  registry:
    image: 'registry:2'
    restart: always
    depends_on:
        - sslproxy
    ports:
            - '5000:5000'
    volumes:
        - './registry-data:/var/lib/registry'
          #            - './certs:/certs'
        - './config.yml:/etc/docker/registry/config.yml'
        - '/etc/letsencrypt:/certs'

  sslproxy:
    image: nginx
    restart: always
    ports:
            - '443:443'
            - '80:80'
    volumes:
    - ./nginx/conf:/etc/nginx
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /srv/challenges:/srv/challenges
